# name: 🚦 Cypress Tests

# on: pull_request

# jobs:
#   cypress-run:
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v4

#       - name: Install dependencies
#         uses: pnpm/action-setup@v4
#         with:
#           version: 9

#       - name: Cypress run
#         uses: cypress-io/github-action@v6
#         with:
#           config: baseUrl=https://inout-git-${{ github.head_ref }}-franck-fernandezs-projects.vercel.app
