name: Cypress Tests

on: pull_request

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cypress run
        uses: cypress-io/github-action@v6
        env:
          config: baseUrl=inout-git-${{ github.head_ref }}-franck-fernandezs-projects.vercel.app
        with:
          wait-on: 'http://localhost:3000'
